### ISSUE TITLE
[iOS] When no hint drop down is invisible

### ISSUE THREAD

**Issue by PeterStaev** [PeterStaev/NativeScript-Drop-Down#104]
Currently if the drop down does not have a hint set and there is no excessive padding, the control is invisible on the UI and the user cannot interact with it.

**Comment by irvelervel** [comment]
I'm having the same issue, only when "hint" is present the labels appears in the dropdown, otherwise it opens blank. Items are correctly bound in the view because if you set an index with [(ngModel)]="selectedIndex" the item is set when the page loads. The hint also does not disappear when you choose an item from the dropdown, I don't know if this behaviour is by design.

**Comment by suresh-selvaraj** [comment]
I am also facing the same issue.

**Comment by PeterStaev** [comment]
Fix will be available in the 3.1 version.
