### ISSUE TITLE
Is there any way to wire up the item change event?

### ISSUE THREAD

**Issue by ryc16** [PeterStaev/NativeScript-Drop-Down#16]
Here is my example:

I would like to repeat ie 5 addresses entry where I would like to use 2 dropdowns. One is for country, another is for State. Also when Country item changed, an event got fired and populate the state dropdown.

```
// xml
// repeat ie 5 address
<Repeater.itemTemplate>
:
<dd:DropDown items="{{ $parents['Page'].countryList }}" selectedIndex="{{ selectedCountryIndex }}" />
<dd:DropDown items="{{ $parents['Page'].stateList }}" selectedIndex="{{ selectedStateIndex }}" />
:
</Repeater.itemTemplate>
```
```
// code:
class Address {
  street:string;
  city:string;
  state:string;
  country:string;
  zip:string;
}

class MyObject extends observable.Observable {
:
  RootObject.addresses: Array<Address>;
:
}
```

Please advice. Appreciate if there is example.

**Comment by PeterStaev** [comment]
Hey @ryc16 , there is no built in itemchange event, but you can achieve this by monitoring the `propertyChange` event of the bound observable. Since I dont see your bound objects, let's assume that the `selectedCountryIndex` property is inside the object instance `foo`. then you should do something like:

```js
foo.on("propertyChange", function (data) {
     switch (data.propertyName)
     {
         case "selectedCountryIndex":
             // do something
             break;
     }     
});
```
