### ISSUE TITLE
How to padding/margin style to drop-down items

### ISSUE THREAD

**Issue by meysam-mahmoodi** [PeterStaev/NativeScript-Drop-Down#187]
Hello
I'd like to set some padding and margin to drop-down items. is there a way to doing that?
thanks

**Comment by PeterStaev** [comment]
@meysam-mahmoodi , currently you cannot add margin/padding ONLY to the items, since item specific css styles is not implemented. You can track #142. 

If you want you can apply margin/padding to the whole drop down which will apply the margin/padding to both the items and the visual that displays the selected item.

**Comment by meysam-mahmoodi** [comment]
@PeterStaev Thank you for replying. It would be amazing to be able to change style items.
