### ISSUE TITLE
Styling the button that creates the drop-down

### ISSUE THREAD

**Issue by hchor** [PeterStaev/NativeScript-Drop-Down#19]
How do I style the button that creates the drop-down? Or even use a StackLayout or something else that initiates the drop-down?

**Comment by PeterStaev** [comment]
Hey @hchor , you cannot directly style the android indicator (it is not a button, since the drop down will open wherever you press inside the drop down). If you want you can add a normal button next to the drop down, style it to whatever fits your design, and then handle the tap event of the button and use the `open()` method of the drop down to open the popup. Hope this helps.

**Comment by Mcdeep** [comment]
Hi all... I just cannot figure out to manage to style the List Items. They all appear squashed. Can you highlight on how to add styles to them. Thanks

**Comment by PeterStaev** [comment]
Hey @Mcdeep, just add `padding` style to the drop down. For reference you can look at the sample app in this repo.

**Comment by hvadotnarola** [comment]
Hey is there method to be called on opening popup and on selection(Closing) ?

**Comment by PeterStaev** [comment]
Hey @hvadotnarola , currently this is not possible. Added an enhancement for a future release. Thanks for your suggestion!
