### ISSUE TITLE
Error: Can't resolve 'nativescript-angular/forms/value-accessors/base-value-accessor' 

### ISSUE THREAD

**Issue by AquilesOliveira** [PeterStaev/NativeScript-Drop-Down#230]
My definitions: 
   "tns-android": {
      "version": "6.2.0"
    },
    "tns-ios": {
      "version": "6.2.0"
    }
  "tns-core-modules": "^6.2.0",
  "tns-platform-declarations": "6.1.2",

**Comment by PeterStaev** [comment]
This is fixed in the new version of the plugin available in the [ProPlugins NPM](https://npm.proplugins.org) registry.

All future work of this plugin will be available exclusively as part of ProPlugins initiative. So if you want to get the latest updates/fixes/features make sure you [subscribe to the service](https://proplugins.org/subscribe.html). You get all my plugins plus many of the most used and high quality plugins for a small monthly subscription fee.
