### ISSUE TITLE
Dropdown is not a valid view instance

### ISSUE THREAD

**Issue by catherine-augustine** [PeterStaev/NativeScript-Drop-Down#250]
Dropdown and angular versions :

 "nativescript-drop-down": "^5.0.6",
 "@nativescript/angular": "8.21.0",

Issue is described here. I tried the solution suggested in the answer. Still I see the error 'Dropdown is not a valid instance'

I am testing in the nativescript preview app by running 'tns preview' 

https://stackoverflow.com/questions/63606742/dropdown-is-not-a-valid-view-instance-angularnativescript/63618073#63618073

**Comment by PeterStaev** [comment]
Hey @catherine-augustine , please try using `tns run` instead of `tns preview`. Multiple people have reported problems that disappeared when they used `tns run` and deployed on a simulator/device locally. Preview is only good when you use only the core plugins. Once you start using custom plugins it is more often a miss than a hit. I personally do not use `tns preview` at all.
