### ISSUE TITLE
error NG6002: Appears in the NgModule.imports of AppModule, but could not be resolved to an NgModule class.

### ISSUE THREAD

**Issue by dasarijit88** [PeterStaev/NativeScript-Drop-Down#256]
ERROR in node_modules/nativescript-drop-down/angular/index.d.ts:17:22 - error NG6002: Appears in the NgModule.imports of AppModule, but could not be resolved to an NgModule class.

This likely means that the library (nativescript-drop-down/angular) which declares DropDownModule has not been processed correctly by ngcc, or is not compatible with Angular Ivy. Check if a newer version of the library is available, and update if so. Also consider checking with the library's authors to see if the library is expected to be compatible with Ivy.

This issue is only happening with iOS for me. I am using  "nativeScriptVersion": "7.0.11",

**Comment by PeterStaev** [comment]
Hey @dasarijit88 , per the readme this plugin is not updated to support NS6 let alone NS7. There is a working version for NS7 under the [ProPlugins](https://proplugins.org/subscribe.html) subscription. If you cannot subscribe, then you can fork the code and try to make it compatible with NS7. I'm happily accepting PRs :) The other solution I can suggest is to change your layout so that you replace the DD with an alternative way of selecting values (for example another screen that shows a ListView from which the user can select their choice).
