### ISSUE TITLE
Dinamyc dropdown generation - selectedIndex

### ISSUE THREAD

**Issue by IvRRimum** [PeterStaev/NativeScript-Drop-Down#33]
Hello,

So i am doing dinamyc dropdown generation. The dropdowns themselves generate perfectly, however selectedIndex acts really weird. They just randomly reset themselves, or remember previous selections( i need unique for each dropbox ).

``` xml
<StackLayout col="0" row="2">
      <ListView [items]="categoryService.bseCategoryNamesArray | async">
        <template let-item="item" let-i="index">
          <GridLayout>
            <DropDown backroundColor="red" #dd [items]="item" [selectedIndex]="categoryService.baseCategorySelected[i]" (selectedIndexChange)="onchange(dd.selectedIndex, i)"></DropDown>
          </GridLayout>
        </template>
     </ListView>
</StackLayout>
```

and
`categoryService.baseCategorySelected[i]` Contains {"0": 0, "1": 0}, even tho i change the selected index, the indexes still show values 0 all the time. But onChange event shows correct selectedIndexes.

So how would one make this work?

**Comment by PeterStaev** [comment]
Hey @IvRRimum , I have not used NG2 extensively, so I'm not able to help you much. But if I test with a `TextField` instead of `DropDown` it again does not persist the values of the `text` property. So my guess is that either two way binding (as the loading of the values work) in templates does not work, or it is done in some other way. Might be best to ask this question in the NativeScript angular repo.

**Comment by PeterStaev** [comment]
No further feedback, so closing this one.
