### ISSUE TITLE
NativeScript Drop Down selectedIndexChange without Angular Partial Solution

### ISSUE THREAD

**Issue by arslanutku** [PeterStaev/NativeScript-Drop-Down#41]
function pageLoaded(args) 
{
    var page = args.object;
    //dropDownID Change your dropdown id.
    var dropDown= page.getViewById("dropDownID");
     dropDown._onSelectedIndexPropertyChanged= () => {
    //here add your function or code..
};

}
exports.pageLoaded = pageLoaded;

**Comment by PeterStaev** [comment]
Hey @arslanutku , although your code will work it will mess up the internal handling of the event, because you override it with your own. So other things will not work. If you really want to use that private method, then you should remember the current one and call it inside yours, so something like:

```ts
function pageLoaded(args) 
{
    var page = args.object;
    //dropDownID Change your dropdown id.
    var dropDown= page.getViewById("dropDownID");
    dropDown._tmp = dropDown._onSelectedIndexPropertyChanged;
    dropDown._onSelectedIndexPropertyChanged= () => {
        dropDown._temp();
        //here add your function or code..
    };

}
exports.pageLoaded = pageLoaded;
```
