### ISSUE TITLE
Implement Style CSS

### ISSUE THREAD

**Issue by Jayuda** [PeterStaev/NativeScript-Drop-Down#8]
How to styling this dropdown ?
Because i am use standart style nativescript not working.
Thanks

**Comment by PeterStaev** [comment]
Hey @Jayuda , what kind of styling are you looking for?

**Comment by Jayuda** [comment]
Thanks for respond @PeterStaev ,
I want implement standart CSS like this : 
```
            <dd:DropDown  row="2" col="1" items="{{ outlets }}" selectedIndex="{{ outlet_SelectedIndex }}" hint="Chose your outlets here"
                          style="font-family: 'Roboto', Roboto;border-color:#009688 !important;color:#009688 !important;"/>

```

Any idea to implement hint, border-color or color for this dropdown ?

**Comment by PeterStaev** [comment]
Currently the {N} framework does not allow to set per-side borders: [NativeScript/issues/859](https://github.com/NativeScript/NativeScript/issues/859). The border that you see on Android comes from the default styling of android native controls. What I (and i think most people of the community) do when I want to set a border is to add a dummy layout with height of 1 with background where I want the border to appear. So in your case it should be something like:
```xml
<dd:DropDown  row="2" col="1" items="{{ outlets }}" selectedIndex="{{ outlet_SelectedIndex }}" hint="Chose your outlets here"
style="font-family: 'Roboto', Roboto;color:#009688;"/>
<GridLayout height="1" style="background-color:#009688;"></GridLayout>
``` 

As for the hint - currently the widget does not have this ability. Will see to add it one of the future versions. Since the android wdiget does not have built in support of hints the following "hack" would have to be used [http://stackoverflow.com/questions/13877681/how-can-i-add-a-hint-to-the-spinner-widget](http://stackoverflow.com/questions/13877681/how-can-i-add-a-hint-to-the-spinner-widget)

**Comment by PeterStaev** [comment]
Added #9 to add a hint property in a future release

**Comment by jilenloa** [comment]
How do I style the options differently on iOS. Example, I want the hint to be left aligned and the options to be center aligned.

**Comment by PeterStaev** [comment]
@jilenloa , currently you cant and there is an enhancement to support different styling:
https://github.com/PeterStaev/NativeScript-Drop-Down/issues/44

For your specific case you can take a look for a workaround at:
https://github.com/PeterStaev/NativeScript-Drop-Down/issues/44
